version: '3.8'

services:
  nodejs:
    container_name: redis_node_app
    command: npm run start:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3500:3500
    volumes:
      - ./:/home/node/redis-node-app/
    depends_on:
      #- redis
      - redis-stack-server
    links:
      #- redis
      - redis-stack-server
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis_db_app
    #command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - 6381:6379
    expose:
      - 6381
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    # networks:
    #   - network
  redis-stack-server:
    container_name: redis-stack-server
    image: redis/redis-stack-server:latest
    command: redis-server --save 20 1 --loglevel warning --protected-mode no --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so
    environment:
      - REDIS_ARGS=--save 1200 32
    volumes:
       - ./redis-stack-data:/data
    ports:
      - 6382:6379
    expose:
      - 6382

networks:
  network:
    driver: bridge
